name: Pulumi Deploy (Production)
on:
  push:
    branches:
      - "release/*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

concurrency:
  group: merge-${{ github.ref }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      UPSTASH_EMAIL: ${{ secrets.UPSTASH_EMAIL }}
      UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: sgcarstrends/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
